# Generated by Django 5.2.3 on 2025-06-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('electro', 'Electrodomésticos'), ('libros', 'Libros'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
