# Generated by Django 5.2.3 on 2025-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_precio_producto_precio_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='recurso',
            field=models.FileField(blank=True, null=True, upload_to='recurso/'),
        ),
    ]
