# Generated by Django 5.2.3 on 2025-06-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('muebles', 'Muebles'), ('moda', 'Moda'), ('decoracion', 'Decoración'), ('electrohogar', 'Electrohogar'), ('otras', 'Otras categorías')], max_length=50),
        ),
    ]
