# Generated by Django 5.2.3 on 2025-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_producto_imagen_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.TextField(default='Sin detalles', verbose_name='Descripción detallada'),
            preserve_default=False,
        ),
    ]
