# Generated by Django 5.2.3 on 2025-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_producto_descripcion_producto_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='principal',
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_productos/'),
        ),
    ]
