# Generated by Django 5.2.3 on 2025-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_imagenproducto_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='recurso',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
