# Generated by Django 5.2.3 on 2025-07-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='recurso',
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='recursos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='productos.producto')),
            ],
        ),
    ]
